"""Add AI Trip Planner models

Revision ID: 5c2a8064ec03
Revises: e43fa38b5d45
Create Date: 2025-11-15 13:36:13.876938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2a8064ec03'
down_revision: Union[str, Sequence[str], None] = 'e43fa38b5d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_session_created', 'ai_sessions', ['created_at'], unique=False)
    op.create_index('idx_ai_session_user_status', 'ai_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_ai_sessions_created_at'), 'ai_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_sessions_session_token'), 'ai_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_ai_sessions_status'), 'ai_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_sessions_user_id'), 'ai_sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_preference_key', 'user_preferences', ['user_id', 'key'], unique=True)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('memory_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('PREFERENCE', 'TRIP_HISTORY', 'BEHAVIOR', 'FEEDBACK', name='memorytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_created', 'memory_events', ['created_at'], unique=False)
    op.create_index('idx_memory_user_type', 'memory_events', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_memory_events_created_at'), 'memory_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_events_type'), 'memory_events', ['type'], unique=False)
    op.create_index(op.f('ix_memory_events_user_id'), 'memory_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_memory_events_vector_id'), 'memory_events', ['vector_id'], unique=False)
    op.create_table('trip_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('travel_class', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('flexibility', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'PLANNED', 'BOOKED_ELSEWHERE', 'CANCELLED', name='tripplanstatus'), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('recommended_flights_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trip_plan_route_date', 'trip_plans', ['origin', 'destination', 'departure_date'], unique=False)
    op.create_index('idx_trip_plan_user_status', 'trip_plans', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_trip_plans_destination'), 'trip_plans', ['destination'], unique=False)
    op.create_index(op.f('ix_trip_plans_origin'), 'trip_plans', ['origin'], unique=False)
    op.create_index(op.f('ix_trip_plans_status'), 'trip_plans', ['status'], unique=False)
    op.create_index(op.f('ix_trip_plans_user_id'), 'trip_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_plans_user_id'), table_name='trip_plans')
    op.drop_index(op.f('ix_trip_plans_status'), table_name='trip_plans')
    op.drop_index(op.f('ix_trip_plans_origin'), table_name='trip_plans')
    op.drop_index(op.f('ix_trip_plans_destination'), table_name='trip_plans')
    op.drop_index('idx_trip_plan_user_status', table_name='trip_plans')
    op.drop_index('idx_trip_plan_route_date', table_name='trip_plans')
    op.drop_table('trip_plans')
    op.drop_index(op.f('ix_memory_events_vector_id'), table_name='memory_events')
    op.drop_index(op.f('ix_memory_events_user_id'), table_name='memory_events')
    op.drop_index(op.f('ix_memory_events_type'), table_name='memory_events')
    op.drop_index(op.f('ix_memory_events_created_at'), table_name='memory_events')
    op.drop_index('idx_memory_user_type', table_name='memory_events')
    op.drop_index('idx_memory_created', table_name='memory_events')
    op.drop_table('memory_events')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index('idx_user_preference_key', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_ai_sessions_user_id'), table_name='ai_sessions')
    op.drop_index(op.f('ix_ai_sessions_status'), table_name='ai_sessions')
    op.drop_index(op.f('ix_ai_sessions_session_token'), table_name='ai_sessions')
    op.drop_index(op.f('ix_ai_sessions_created_at'), table_name='ai_sessions')
    op.drop_index('idx_ai_session_user_status', table_name='ai_sessions')
    op.drop_index('idx_ai_session_created', table_name='ai_sessions')
    op.drop_table('ai_sessions')
    # ### end Alembic commands ###
