"""add_performance_indexes

Revision ID: e43fa38b5d45
Revises: 
Create Date: 2025-10-02 11:54:30.013714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43fa38b5d45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iata_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('is_widebody', sa.Boolean(), nullable=True),
    sa.Column('typical_seats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_iata_code'), 'aircraft', ['iata_code'], unique=True)
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iata_code', sa.CHAR(length=2), nullable=False),
    sa.Column('icao_code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('alliance', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('is_low_cost', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icao_code')
    )
    op.create_index(op.f('ix_airlines_alliance'), 'airlines', ['alliance'], unique=False)
    op.create_index(op.f('ix_airlines_iata_code'), 'airlines', ['iata_code'], unique=True)
    op.create_index(op.f('ix_airlines_is_active'), 'airlines', ['is_active'], unique=False)
    op.create_index(op.f('ix_airlines_is_low_cost'), 'airlines', ['is_low_cost'], unique=False)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iata_code', sa.CHAR(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icao_code')
    )
    op.create_index('idx_airport_city_active', 'airports', ['city', 'is_active'], unique=False)
    op.create_index('idx_airport_city_country', 'airports', ['city', 'country'], unique=False)
    op.create_index('idx_airport_coordinates', 'airports', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_airports_city'), 'airports', ['city'], unique=False)
    op.create_index(op.f('ix_airports_country'), 'airports', ['country'], unique=False)
    op.create_index(op.f('ix_airports_country_code'), 'airports', ['country_code'], unique=False)
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=True)
    op.create_index(op.f('ix_airports_is_active'), 'airports', ['is_active'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=True),
    sa.Column('api_enabled', sa.Boolean(), nullable=True),
    sa.Column('deeplink_template', sa.Text(), nullable=True),
    sa.Column('commission_model', sa.String(length=50), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('commission_currency', sa.String(length=3), nullable=True),
    sa.Column('api_credentials', sa.JSON(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_is_self'), 'partners', ['is_self'], unique=False)
    op.create_index(op.f('ix_partners_name'), 'partners', ['name'], unique=True)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('lowest_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=True),
    sa.Column('passengers_adults', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_route_date', 'price_snapshots', ['origin', 'destination', 'departure_date', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_destination'), 'price_snapshots', ['destination'], unique=False)
    op.create_index(op.f('ix_price_snapshots_origin'), 'price_snapshots', ['origin'], unique=False)
    op.create_index(op.f('ix_price_snapshots_recorded_at'), 'price_snapshots', ['recorded_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_booking_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_source', sa.Enum('METASEARCH_REDIRECT', 'DIRECT_BOOKING', name='bookingsource'), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CLICK_INITIATED', 'PARTNER_CONFIRMED', 'PENDING_PAYMENT', 'PAYMENT_PROCESSING', 'CONFIRMED', 'TICKETED', 'CANCELLED', 'REFUNDED', 'FAILED', name='bookingstatus'), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('partner_booking_ref', sa.String(length=255), nullable=True),
    sa.Column('partner_deeplink', sa.Text(), nullable=True),
    sa.Column('commission_expected', sa.Float(), nullable=True),
    sa.Column('commission_earned', sa.Float(), nullable=True),
    sa.Column('commission_currency', sa.String(length=3), nullable=True),
    sa.Column('pnr', sa.String(length=20), nullable=True),
    sa.Column('ticket_numbers', sa.JSON(), nullable=True),
    sa.Column('raw_flight_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_route', 'bookings', ['origin', 'destination', 'departure_date'], unique=False)
    op.create_index('idx_booking_source_status', 'bookings', ['booking_source', 'status'], unique=False)
    op.create_index('idx_booking_user_date', 'bookings', ['user_id', 'departure_date'], unique=False)
    op.create_index(op.f('ix_bookings_booking_source'), 'bookings', ['booking_source'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_destination'), 'bookings', ['destination'], unique=False)
    op.create_index(op.f('ix_bookings_internal_booking_id'), 'bookings', ['internal_booking_id'], unique=True)
    op.create_index(op.f('ix_bookings_origin'), 'bookings', ['origin'], unique=False)
    op.create_index(op.f('ix_bookings_partner_booking_ref'), 'bookings', ['partner_booking_ref'], unique=False)
    op.create_index(op.f('ix_bookings_pnr'), 'bookings', ['pnr'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('partner_deeplink', sa.Text(), nullable=False),
    sa.Column('flight_offer_snapshot', sa.JSON(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('commission_expected', sa.Float(), nullable=True),
    sa.Column('commission_earned', sa.Float(), nullable=True),
    sa.Column('conversion_tracked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_click_partner_converted', 'clicks', ['partner_name', 'converted'], unique=False)
    op.create_index('idx_click_route', 'clicks', ['origin', 'destination', 'departure_date'], unique=False)
    op.create_index('idx_click_session_date', 'clicks', ['session_id', 'clicked_at'], unique=False)
    op.create_index(op.f('ix_clicks_clicked_at'), 'clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_clicks_converted'), 'clicks', ['converted'], unique=False)
    op.create_index(op.f('ix_clicks_destination'), 'clicks', ['destination'], unique=False)
    op.create_index(op.f('ix_clicks_origin'), 'clicks', ['origin'], unique=False)
    op.create_index(op.f('ix_clicks_session_id'), 'clicks', ['session_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('passengers_adults', sa.Integer(), nullable=True),
    sa.Column('passengers_children', sa.Integer(), nullable=True),
    sa.Column('passengers_infants', sa.Integer(), nullable=True),
    sa.Column('cabin_class', sa.String(length=20), nullable=True),
    sa.Column('search_name', sa.String(length=100), nullable=True),
    sa.Column('is_price_alert', sa.Boolean(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('alert_currency', sa.String(length=3), nullable=True),
    sa.Column('alert_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_triggered_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_active_expires', 'saved_searches', ['is_price_alert', 'is_active', 'expires_at'], unique=False)
    op.create_index('idx_search_user_active', 'saved_searches', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_saved_searches_is_price_alert'), 'saved_searches', ['is_price_alert'], unique=False)
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('booking_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('is_return', sa.Boolean(), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('departure_airport', sa.String(length=3), nullable=False),
    sa.Column('arrival_airport', sa.String(length=3), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cabin_class', sa.String(length=50), nullable=True),
    sa.Column('fare_class', sa.String(length=10), nullable=True),
    sa.Column('booking_class', sa.String(length=2), nullable=True),
    sa.Column('baggage_allowance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['arrival_airport'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['departure_airport'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segment_booking_order', 'booking_segments', ['booking_id', 'segment_order'], unique=False)
    op.create_index(op.f('ix_booking_segments_booking_id'), 'booking_segments', ['booking_id'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('CLICK_INITIATED', 'PARTNER_CONFIRMED', 'PENDING_PAYMENT', 'PAYMENT_PROCESSING', 'CONFIRMED', 'TICKETED', 'CANCELLED', 'REFUNDED', 'FAILED', name='bookingstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('CLICK_INITIATED', 'PARTNER_CONFIRMED', 'PENDING_PAYMENT', 'PAYMENT_PROCESSING', 'CONFIRMED', 'TICKETED', 'CANCELLED', 'REFUNDED', 'FAILED', name='bookingstatus'), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('booking_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_history_booking_time', 'booking_status_history', ['booking_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_status_history_changed_at'), 'booking_status_history', ['changed_at'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('passenger_type', sa.Enum('ADULT', 'CHILD', 'INFANT', name='passengertype'), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('passport_expiry_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_booking_id'), 'passengers', ['booking_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'CLICK', 'PAYME', 'PAYPAL', 'BANK_TRANSFER', name='paymentprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('refunded_amount', sa.Float(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_provider_status', 'payments', ['provider', 'status'], unique=False)
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payments_provider_transaction_id'), 'payments', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_index('idx_payment_provider_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_passengers_booking_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_booking_status_history_changed_at'), table_name='booking_status_history')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_index('idx_status_history_booking_time', table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index(op.f('ix_booking_segments_booking_id'), table_name='booking_segments')
    op.drop_index('idx_segment_booking_order', table_name='booking_segments')
    op.drop_table('booking_segments')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_index(op.f('ix_saved_searches_is_price_alert'), table_name='saved_searches')
    op.drop_index('idx_search_user_active', table_name='saved_searches')
    op.drop_index('idx_alert_active_expires', table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_clicks_session_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_origin'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_destination'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_converted'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_clicked_at'), table_name='clicks')
    op.drop_index('idx_click_session_date', table_name='clicks')
    op.drop_index('idx_click_route', table_name='clicks')
    op.drop_index('idx_click_partner_converted', table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pnr'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_partner_booking_ref'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_origin'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_internal_booking_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_destination'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_source'), table_name='bookings')
    op.drop_index('idx_booking_user_date', table_name='bookings')
    op.drop_index('idx_booking_source_status', table_name='bookings')
    op.drop_index('idx_booking_route', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_snapshots_recorded_at'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_origin'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_destination'), table_name='price_snapshots')
    op.drop_index('idx_price_route_date', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_partners_name'), table_name='partners')
    op.drop_index(op.f('ix_partners_is_self'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_airports_is_active'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_country_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_country'), table_name='airports')
    op.drop_index(op.f('ix_airports_city'), table_name='airports')
    op.drop_index('idx_airport_coordinates', table_name='airports')
    op.drop_index('idx_airport_city_country', table_name='airports')
    op.drop_index('idx_airport_city_active', table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_is_low_cost'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_is_active'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_iata_code'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_alliance'), table_name='airlines')
    op.drop_table('airlines')
    op.drop_index(op.f('ix_aircraft_iata_code'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
